# categories.py

CATEGORY_DICT = {
    '1': 'Electronics',
    '1.1': 'Phones & Accessories',
    '1.2': 'Laptops & Computers',
    '1.3': 'Tablets',
    '1.4': 'Cameras & Camcorders',
    '1.5': 'Audio & Headphones',
    '1.6': 'Wearable Technology',
    '1.7': 'Home Appliances',
    '2': 'Clothing, Shoes & Accessories',
    '2.1': 'Men’s Clothing',
    '2.2': 'Women’s Clothing',
    '2.3': 'Kids’ Clothing',
    '2.4': 'Shoes',
    '2.5': 'Accessories',
    '3': 'Home, Furniture & Appliances',
    '3.1': 'Furniture',
    '3.2': 'Home Decor',
    '3.3': 'Kitchen & Dining',
    '3.4': 'Bedding & Mattresses',
    '3.5': 'Appliances',
    '4': 'Health & Beauty',
    '4.1': 'Personal Care',
    '4.2': 'Health & Wellness',
    '4.3': 'Makeup',
    '4.4': 'Skincare',
    '4.5': 'Haircare',
    '5': 'Toys, Games & Video Games',
    '5.1': 'Toys',
    '5.2': 'Games',
    '5.3': 'Video Games & Consoles',
    '6': 'Groceries',
    '6.1': 'Fresh Food',
    '6.2': 'Pantry Staples',
    '6.3': 'Beverages',
    '6.4': 'Snacks',
    '6.5': 'Household Essentials',
    '7': 'Sports & Outdoors',
    '7.1': 'Exercise & Fitness Equipment',
    '7.2': 'Outdoor Recreation',
    '7.3': 'Sports Apparel',
    '7.4': 'Camping & Hiking Gear',
    '8': 'Automotive',
    '8.1': 'Car Electronics & GPS',
    '8.2': 'Car Care',
    '8.3': 'Tires & Wheels',
    '8.4': 'Tools & Equipment'
}
